title: Lolev
email: info@lolev.beer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lolev.beer" # the base hostname & protocol for your site, e.g. http://example.com
logo: assets/lolev.jpg
image: site

kramdown:
  input: GFM

sass:
  sass_dir: _sass
  style: compressed

page_gen-dirs: true

collections:
  - sections

collections:
  sections:
    output: true

page_gen:
- data: people
  template: digicard
  name: first
  debug: false

page_gen:
- data: people
  template: signature
  dir: signature
  name: first
  debug: false

- data: beer
  template: qr
  dir: qr
  name_expr: record['variant'] || ""
  debug: false

- data: beer
  template: barcode
  dir: barcode
  name_expr: record['variant'] || ""
  debug: false

- data: beer
  template: beer
  title: name
  name_expr: record['variant'] || ""
  debug: false

- data: people
  template: contact
  name: first
  extension: vcf
  debug: false
