/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    beers: Beer;
    'beer-reviews': BeerReview;
    styles: Style;
    tags: Tag;
    menus: Menu;
    products: Product;
    events: Event;
    'donation-requests': DonationRequest;
    jobs: Job;
    'job-applications': JobApplication;
    'recurring-events': RecurringEvent;
    food: Food;
    'food-vendors': FoodVendor;
    'recurring-food-schedules': RecurringFoodSchedule;
    'recurring-food-exclusions': RecurringFoodExclusion;
    users: User;
    locations: Location;
    'holiday-hours': HolidayHour;
    distributors: Distributor;
    faqs: Faq;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    beers: {
      reviews: 'beer-reviews';
    };
  };
  collectionsSelect: {
    beers: BeersSelect<false> | BeersSelect<true>;
    'beer-reviews': BeerReviewsSelect<false> | BeerReviewsSelect<true>;
    styles: StylesSelect<false> | StylesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'donation-requests': DonationRequestsSelect<false> | DonationRequestsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'job-applications': JobApplicationsSelect<false> | JobApplicationsSelect<true>;
    'recurring-events': RecurringEventsSelect<false> | RecurringEventsSelect<true>;
    food: FoodSelect<false> | FoodSelect<true>;
    'food-vendors': FoodVendorsSelect<false> | FoodVendorsSelect<true>;
    'recurring-food-schedules': RecurringFoodSchedulesSelect<false> | RecurringFoodSchedulesSelect<true>;
    'recurring-food-exclusions': RecurringFoodExclusionsSelect<false> | RecurringFoodExclusionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'holiday-hours': HolidayHoursSelect<false> | HolidayHoursSelect<true>;
    distributors: DistributorsSelect<false> | DistributorsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'coming-soon': ComingSoon;
    'recurring-food': RecurringFood;
    'site-content': SiteContent;
    'site-seo': SiteSeo;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'coming-soon': ComingSoonSelect<false> | ComingSoonSelect<true>;
    'recurring-food': RecurringFoodSelect<false> | RecurringFoodSelect<true>;
    'site-content': SiteContentSelect<false> | SiteContentSelect<true>;
    'site-seo': SiteSeoSelect<false> | SiteSeoSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
    'collection-query': CollectionQueryWidget;
    activity: ActivityWidget;
  };
  user: User;
  jobs: {
    tasks: {
      syncUntappdRatings: TaskSyncUntappdRatings;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beers".
 */
export interface Beer {
  id: string;
  /**
   * The last person to save this. Automated updates, such as the nightly Untappd sync, keep the previous person.
   */
  updatedBy?: (string | null) | User;
  name: string;
  style: string | Style;
  glass: 'pint' | 'stein' | 'teku' | 'uha';
  abv: number;
  description?: string | null;
  hops?: string | null;
  /**
   * Optional (search existing or add a new one)
   */
  tag?: (string | null) | Tag;
  draftPrice: number;
  /**
   * Set automatically from the draft price unless "Half Pour Only" is on
   */
  halfPour?: number | null;
  /**
   * Served in half pours only: hides the full draft price on the site and uses the half pour price above as entered.
   */
  halfPourOnly?: boolean | null;
  fourPack?: number | null;
  /**
   * Set automatically from the four pack price
   */
  canSingle?: number | null;
  bottlePrice?: number | null;
  upc?: string | null;
  /**
   * Beer image (auto-filled by the 3D label tool; upload to override)
   */
  image?: (string | null) | Media;
  /**
   * Generated 3D label texture
   */
  labelBase?: (string | null) | Media;
  /**
   * Generated metalness map (white = metallic foil)
   */
  labelMetalness?: (string | null) | Media;
  /**
   * Generated can-rotation sprite sheet (PNG; animated in CSS on menu displays)
   */
  labelVideo?: (string | null) | Media;
  /**
   * Untappd URL (e.g., /b/lolev-beer-lupula/123456)
   */
  untappd?: string | null;
  /**
   * Rating (auto-fetched)
   */
  untappdRating?: number | null;
  /**
   * Rating count (auto-fetched)
   */
  untappdRatingCount?: number | null;
  /**
   * Top Beer Drops URL (e.g., https://topbeerdrops.com/...)
   */
  topBeerDrops?: string | null;
  reviews?: {
    docs?: (string | BeerReview)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Hide from the /beer catalog (and sitemap/feeds). Usually for guest beers. Does NOT hide the beer from menu displays (/m).
   */
  hideFromSite?: boolean | null;
  /**
   * Collaboration brew with another brewery. Shows a "Collab" badge instead of the automatic "Just Released" one.
   */
  collab?: boolean | null;
  /**
   * Brewery name shown in the collaboration badge. Leave blank to show “Collab”.
   */
  collabBrewery?: string | null;
  /**
   * Auto-generated from name, but you can override it manually
   */
  slug: string;
  /**
   * Assigned automatically to new beers; change only to fix a mistake (must be unique)
   */
  recipe?: number | null;
  /**
   * Legacy review data retained temporarily for migration compatibility.
   */
  positiveReviews?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Optional overrides for this document’s public page. Blank fields keep the auto-generated title and description.
   */
  seo?: {
    /**
     * Browser tab and SERP title. Leave blank to keep the auto-generated title. Do not append "• Lolev Beer" on hub pages; the site title template adds it.
     */
    title?: string | null;
    /**
     * SERP snippet. Aim for ~150–160 characters.
     */
    description?: string | null;
    /**
     * Optional. Defaults to the meta title (plus site name where applicable).
     */
    ogTitle?: string | null;
    /**
     * Optional. Defaults to the meta description.
     */
    ogDescription?: string | null;
    /**
     * Optional social share image (1200×630 recommended). Falls back to the site default.
     */
    ogImage?: (string | null) | Media;
    /**
     * Optional. Press Enter after each keyword. Mostly legacy; Google ignores these.
     */
    keywords?: string[] | null;
    /**
     * Ask search engines not to list this page in results. Links on it are still followed, and it is left out of the sitemap.
     */
    noIndex?: boolean | null;
    /**
     * Optional override, e.g. /beer or /lawrenceville. Must start with /. Leave blank for the normal URL.
     */
    canonicalPath?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  /**
   * Slack member ID (e.g. U01ABCDEF). Filled in automatically when the Slack profile email matches this account — set it manually only if the emails differ.
   */
  slackUserId?: string | null;
  /**
   * Assign bartenders to the locations whose menus they may access. Users without an assignment cannot access menu drafts.
   */
  locations?: (string | Location)[] | null;
  /**
   * Admins can manage users and all content. Event/Beer/Food Managers can manage their respective collections. Lead Bartenders can update line cleaning dates. Bartenders can update menus. Users can have multiple roles.
   */
  roles: ('admin' | 'event-manager' | 'beer-manager' | 'food-manager' | 'lead-bartender' | 'bartender')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: string;
  markLinesCleanedToday?: boolean | null;
  /**
   * Admin correction: choose a date, then save this location.
   */
  linesLastCleaned?: string | null;
  /**
   * Is this location currently active?
   */
  active?: boolean | null;
  name: string;
  /**
   * The draft menu shown for this location on the homepage and /<location> page (e.g. /lawrenceville). Only published menus appear. Leave blank to hide it.
   */
  draftMenu?: (string | null) | Menu;
  /**
   * The cans menu shown for this location on the homepage and /<location> page (e.g. /lawrenceville). Only published menus appear. Leave blank to hide it.
   */
  cansMenu?: (string | null) | Menu;
  /**
   * Optional short paragraph under the location heading for local SEO. Leave blank to show nothing.
   */
  intro?: string | null;
  /**
   * Timezone for this location's hours
   */
  timezone?: ('America/New_York' | 'America/Chicago' | 'America/Denver' | 'America/Los_Angeles') | null;
  /**
   * Auto-generated from name (lowercase, spaces to dashes)
   */
  slug?: string | null;
  basicInfo?: {
    phone?: string | null;
    email?: string | null;
  };
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
    /**
     * Custom Google Maps or directions link for this location
     */
    directionsUrl?: string | null;
  };
  /**
   * Longitude, Latitude (e.g. -79.960098, 40.465372)
   *
   * @minItems 2
   * @maxItems 2
   */
  coordinates?: [number, number] | null;
  images?: {
    /**
     * Image shown on location cards (recommended: 800x600px)
     */
    card?: (string | null) | Media;
    /**
     * Hero/banner image for this location (recommended: 1920x1080px)
     */
    hero?: (string | null) | Media;
  };
  monday?: {
    open?: string | null;
    close?: string | null;
  };
  tuesday?: {
    open?: string | null;
    close?: string | null;
  };
  wednesday?: {
    open?: string | null;
    close?: string | null;
  };
  thursday?: {
    open?: string | null;
    close?: string | null;
  };
  friday?: {
    open?: string | null;
    close?: string | null;
  };
  saturday?: {
    open?: string | null;
    close?: string | null;
  };
  sunday?: {
    open?: string | null;
    close?: string | null;
  };
  /**
   * Optional overrides for this document’s public page. Blank fields keep the auto-generated title and description.
   */
  seo?: {
    /**
     * Browser tab and SERP title. Leave blank to keep the auto-generated title. Do not append "• Lolev Beer" on hub pages; the site title template adds it.
     */
    title?: string | null;
    /**
     * SERP snippet. Aim for ~150–160 characters.
     */
    description?: string | null;
    /**
     * Optional. Defaults to the meta title (plus site name where applicable).
     */
    ogTitle?: string | null;
    /**
     * Optional. Defaults to the meta description.
     */
    ogDescription?: string | null;
    /**
     * Optional social share image (1200×630 recommended). Falls back to the site default.
     */
    ogImage?: (string | null) | Media;
    /**
     * Optional. Press Enter after each keyword. Mostly legacy; Google ignores these.
     */
    keywords?: string[] | null;
    /**
     * Ask search engines not to list this page in results. Links on it are still followed, and it is left out of the sitemap.
     */
    noIndex?: boolean | null;
    /**
     * Optional override, e.g. /beer or /lawrenceville. Must start with /. Leave blank for the normal URL.
     */
    canonicalPath?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: string;
  /**
   * The last person to save this. Automated updates, such as the nightly Untappd sync, keep the previous person.
   */
  updatedBy?: (string | null) | User;
  /**
   * Menu name (e.g., "Lawrenceville Draft Menu")
   */
  name: string;
  /**
   * Menu description
   */
  description?: string | null;
  /**
   * Required to generate menu URL
   */
  location: string | Location;
  type: 'cans' | 'draft' | 'other';
  /**
   * Auto-generated from location and type, but you can override it manually
   */
  url: string;
  /**
   * Override automatic day/night theme switching
   */
  themeMode?: ('auto' | 'light' | 'dark') | null;
  /**
   * Play the rotating-can animation on this display. Turn off to show static can images instead.
   */
  animateCans?: boolean | null;
  items: {
    product?:
      | ({
          relationTo: 'beers';
          value: string | Beer;
        } | null)
      | ({
          relationTo: 'products';
          value: string | Product;
        } | null);
    /**
     * Sale Price (optional override)
     */
    price?: string | null;
    /**
     * Optional promotion shown only on the fullscreen can menu.
     */
    promotion?: string | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  description?: string | null;
  /**
   * Optional grouping on Other Things menus. Uncategorized products remain visible.
   */
  category?: ('cocktails-cider' | 'soft-drinks' | 'snacks-merch') | null;
  /**
   * Press "Enter" or "Tab" after entering option to add another
   */
  options?: string[] | null;
  /**
   * Alcohol by volume (%)
   */
  abv?: number | null;
  /**
   * Display price (e.g., "$5.00")
   */
  price?: string | null;
  /**
   * Product from another brewery. Shows "Guest Tap" badge on menu.
   */
  guestTap?: boolean | null;
  /**
   * Collaboration product. Shows "Collab" badge on menu.
   */
  collab?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alternative text for the image (for accessibility)
   */
  alt: string;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    detail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "styles".
 */
export interface Style {
  id: string;
  /**
   * Beer style name (e.g., IPA, Stout, Pale Ale)
   */
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  /**
   * Tag name (e.g., Seasonal, Limited, Award Winner)
   */
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beer-reviews".
 */
export interface BeerReview {
  id: string;
  beer: string | Beer;
  reviewer: string;
  rating: number;
  text: string;
  reviewedAt?: string | null;
  /**
   * Original date text supplied by Untappd when an exact timestamp is unavailable.
   */
  sourceDate?: string | null;
  source: 'untappd';
  sourceUrl: string;
  externalImageUrl?: string | null;
  /**
   * Approved reviews can be included in public beer data.
   */
  approved: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  /**
   * Public events will be displayed on the site
   */
  visibility: 'public' | 'private';
  /**
   * If this is a public event, this will be listed on the website
   */
  organizer: string;
  date: string;
  startTime?: string | null;
  endTime?: string | null;
  location: string | Location;
  /**
   * This will be linked on the website
   */
  site?: string | null;
  tags?: ('music' | 'utensils' | 'puzzle' | 'sports' | 'beer-release' | 'mic-vocal')[] | null;
  description?: string | null;
  /**
   * Optional photo for Event rich results (falls back to the site OG image)
   */
  image?: (string | null) | Media;
  /**
   * Expected or registered attendees
   */
  attendees?: number | null;
  pointOfContact?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Additional information for private event
   */
  otherInfo?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Public donation asks from /donate. Completing the form is not a yes. Rows are created only by the public form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-requests".
 */
export interface DonationRequest {
  id: string;
  status?: ('new' | 'approved' | 'declined') | null;
  askType: 'product' | 'taproom-night';
  organizationName: string;
  contactName: string;
  email: string;
  phone: string;
  mission: string;
  howHeard: string;
  previousDonation: 'yes' | 'no';
  eventName: string;
  eventDate: string;
  venue: string;
  attendees: number;
  requestDetails: string;
  howServed?: string | null;
  recognition: string;
  whyLolev: string;
  pickupName?: string | null;
  /**
   * Location slug from the public form, when the ask is a taproom night.
   */
  taproom?: string | null;
  /**
   * When the #events ping succeeded. Empty means staff should check Slack.
   */
  slackNotifiedAt?: string | null;
  slackError?: string | null;
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Openings listed at /jobs (footer link). Applications land in Job Applications.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: string;
  title: string;
  /**
   * Auto-generated from the title if left blank.
   */
  slug?: string | null;
  location: string | Location;
  employmentType?: ('full-time' | 'part-time' | 'seasonal') | null;
  /**
   * One or two lines on the taproom page.
   */
  summary?: string | null;
  description: string;
  /**
   * Optional last day to apply. Sent to Google as the posting’s expiry. This does not hide the job: also untick Active when it closes.
   */
  closesOn?: string | null;
  active?: boolean | null;
  /**
   * Optional overrides for this document’s public page. Blank fields keep the auto-generated title and description.
   */
  seo?: {
    /**
     * Browser tab and SERP title. Leave blank to keep the auto-generated title. Do not append "• Lolev Beer" on hub pages; the site title template adds it.
     */
    title?: string | null;
    /**
     * SERP snippet. Aim for ~150–160 characters.
     */
    description?: string | null;
    /**
     * Optional. Defaults to the meta title (plus site name where applicable).
     */
    ogTitle?: string | null;
    /**
     * Optional. Defaults to the meta description.
     */
    ogDescription?: string | null;
    /**
     * Optional social share image (1200×630 recommended). Falls back to the site default.
     */
    ogImage?: (string | null) | Media;
    /**
     * Optional. Press Enter after each keyword. Mostly legacy; Google ignores these.
     */
    keywords?: string[] | null;
    /**
     * Ask search engines not to list this page in results. Links on it are still followed, and it is left out of the sitemap.
     */
    noIndex?: boolean | null;
    /**
     * Optional override, e.g. /beer or /lawrenceville. Must start with /. Leave blank for the normal URL.
     */
    canonicalPath?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Applications from /jobs/[slug]. Completing the form is not a hire.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications".
 */
export interface JobApplication {
  id: string;
  job: string | Job;
  name: string;
  email: string;
  phone: string;
  message: string;
  slackNotifiedAt?: string | null;
  slackError?: string | null;
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage events that repeat monthly without creating a dated event for every occurrence.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recurring-events".
 */
export interface RecurringEvent {
  id: string;
  active: boolean;
  /**
   * Public events will be displayed on the site
   */
  visibility: 'public' | 'private';
  /**
   * If this is a public event, this will be listed on the website
   */
  organizer: string;
  year: number;
  day: 'sunday' | 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday';
  /**
   * Choose one or more, such as first and third.
   */
  occurrences: ('first' | 'second' | 'third' | 'fourth' | 'fifth')[];
  location: string | Location;
  startTime?: string | null;
  endTime?: string | null;
  /**
   * Optional dates in this year when the recurring event will not happen.
   */
  excludedDates?:
    | {
        date: string;
        id?: string | null;
      }[]
    | null;
  /**
   * This will be linked on the website
   */
  site?: string | null;
  tags?: ('music' | 'utensils' | 'puzzle' | 'sports' | 'beer-release' | 'mic-vocal')[] | null;
  description?: string | null;
  /**
   * Optional photo for Event rich results (falls back to the site OG image)
   */
  image?: (string | null) | Media;
  /**
   * Expected or registered attendees
   */
  attendees?: number | null;
  pointOfContact?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Additional information for private event
   */
  otherInfo?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food".
 */
export interface Food {
  id: string;
  /**
   * Select food vendor
   */
  vendor: string | FoodVendor;
  /**
   * Auto-populated vendor name for display
   */
  vendorName?: string | null;
  date: string;
  location: string | Location;
  startTime?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food-vendors".
 */
export interface FoodVendor {
  id: string;
  name: string;
  email?: string | null;
  phone?: string | null;
  site?: string | null;
  logo?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recurring-food-schedules".
 */
export interface RecurringFoodSchedule {
  id: string;
  location: string | Location;
  year: number;
  vendor: string | FoodVendor;
  day: 'sunday' | 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday';
  occurrence: 'first' | 'second' | 'third' | 'fourth' | 'fifth';
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recurring-food-exclusions".
 */
export interface RecurringFoodExclusion {
  id: string;
  location: string | Location;
  date: string;
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Holiday and special hours overrides for locations
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "holiday-hours".
 */
export interface HolidayHour {
  id: string;
  /**
   * Name for this override (e.g., "Christmas Day", "New Year's Eve")
   */
  name: string;
  /**
   * Which location(s) this override applies to
   */
  locations: (string | Location)[];
  /**
   * The date this override applies to
   */
  date: string;
  /**
   * Type of override
   */
  type: 'closed' | 'modified';
  /**
   * Override hours (only used when type is "Modified Hours")
   */
  hours?: {
    /**
     * Opening time
     */
    open?: string | null;
    /**
     * Closing time
     */
    close?: string | null;
  };
  /**
   * Optional note to display (e.g., "Closed for the holiday")
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributors".
 */
export interface Distributor {
  id: string;
  /**
   * Business or location name
   */
  name: string;
  /**
   * Full street address
   */
  address: string;
  /**
   * City name
   */
  city?: string | null;
  /**
   * State abbreviation (e.g., PA, NY)
   */
  state?: string | null;
  /**
   * ZIP code
   */
  zip?: string | null;
  /**
   * Type of customer/location
   */
  customerType?: ('Retail' | 'On Premise' | 'Home-D') | null;
  /**
   * Geographic region (a US state or DC); the CSV import defaults it to the state
   */
  region?:
    | (
        | 'AL'
        | 'AK'
        | 'AZ'
        | 'AR'
        | 'CA'
        | 'CO'
        | 'CT'
        | 'DE'
        | 'DC'
        | 'FL'
        | 'GA'
        | 'HI'
        | 'ID'
        | 'IL'
        | 'IN'
        | 'IA'
        | 'KS'
        | 'KY'
        | 'LA'
        | 'ME'
        | 'MD'
        | 'MA'
        | 'MI'
        | 'MN'
        | 'MS'
        | 'MO'
        | 'MT'
        | 'NE'
        | 'NV'
        | 'NH'
        | 'NJ'
        | 'NM'
        | 'NY'
        | 'NC'
        | 'ND'
        | 'OH'
        | 'OK'
        | 'OR'
        | 'PA'
        | 'RI'
        | 'SC'
        | 'SD'
        | 'TN'
        | 'TX'
        | 'UT'
        | 'VT'
        | 'VA'
        | 'WA'
        | 'WV'
        | 'WI'
        | 'WY'
      )
    | null;
  /**
   * Geographic coordinates [longitude, latitude]
   *
   * @minItems 2
   * @maxItems 2
   */
  location: [number, number];
  /**
   * Contact phone number
   */
  phone?: string | null;
  /**
   * Website URL
   */
  website?: string | null;
  /**
   * Whether this location is currently active
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Additional FAQs that will be appended to the default FAQs on the FAQ page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  /**
   * The question being asked
   */
  question: string;
  /**
   * The answer to the question
   */
  answer: string;
  /**
   * Lower numbers appear first. Default FAQs start at 0, so use 100+ to append at the end.
   */
  order?: number | null;
  /**
   * Uncheck to hide this FAQ from the site
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'syncUntappdRatings';
        taskID: string;
        input:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        parent?: {
          taskSlug?: ('inline' | 'syncUntappdRatings') | null;
          taskID?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'syncUntappdRatings') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processingUntil?: string | null;
  processingToken?: string | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'beers';
        value: string | Beer;
      } | null)
    | ({
        relationTo: 'beer-reviews';
        value: string | BeerReview;
      } | null)
    | ({
        relationTo: 'styles';
        value: string | Style;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'menus';
        value: string | Menu;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'donation-requests';
        value: string | DonationRequest;
      } | null)
    | ({
        relationTo: 'jobs';
        value: string | Job;
      } | null)
    | ({
        relationTo: 'job-applications';
        value: string | JobApplication;
      } | null)
    | ({
        relationTo: 'recurring-events';
        value: string | RecurringEvent;
      } | null)
    | ({
        relationTo: 'food';
        value: string | Food;
      } | null)
    | ({
        relationTo: 'food-vendors';
        value: string | FoodVendor;
      } | null)
    | ({
        relationTo: 'recurring-food-schedules';
        value: string | RecurringFoodSchedule;
      } | null)
    | ({
        relationTo: 'recurring-food-exclusions';
        value: string | RecurringFoodExclusion;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'locations';
        value: string | Location;
      } | null)
    | ({
        relationTo: 'holiday-hours';
        value: string | HolidayHour;
      } | null)
    | ({
        relationTo: 'distributors';
        value: string | Distributor;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beers_select".
 */
export interface BeersSelect<T extends boolean = true> {
  updatedBy?: T;
  name?: T;
  style?: T;
  glass?: T;
  abv?: T;
  description?: T;
  hops?: T;
  tag?: T;
  draftPrice?: T;
  halfPour?: T;
  halfPourOnly?: T;
  fourPack?: T;
  canSingle?: T;
  bottlePrice?: T;
  upc?: T;
  image?: T;
  labelBase?: T;
  labelMetalness?: T;
  labelVideo?: T;
  untappd?: T;
  untappdRating?: T;
  untappdRatingCount?: T;
  topBeerDrops?: T;
  reviews?: T;
  hideFromSite?: T;
  collab?: T;
  collabBrewery?: T;
  slug?: T;
  recipe?: T;
  positiveReviews?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        keywords?: T;
        noIndex?: T;
        canonicalPath?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beer-reviews_select".
 */
export interface BeerReviewsSelect<T extends boolean = true> {
  beer?: T;
  reviewer?: T;
  rating?: T;
  text?: T;
  reviewedAt?: T;
  sourceDate?: T;
  source?: T;
  sourceUrl?: T;
  externalImageUrl?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "styles_select".
 */
export interface StylesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  updatedBy?: T;
  name?: T;
  description?: T;
  location?: T;
  type?: T;
  url?: T;
  themeMode?: T;
  animateCans?: T;
  items?:
    | T
    | {
        product?: T;
        price?: T;
        promotion?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  category?: T;
  options?: T;
  abv?: T;
  price?: T;
  guestTap?: T;
  collab?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  visibility?: T;
  organizer?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  location?: T;
  site?: T;
  tags?: T;
  description?: T;
  image?: T;
  attendees?: T;
  pointOfContact?: T;
  email?: T;
  phone?: T;
  otherInfo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-requests_select".
 */
export interface DonationRequestsSelect<T extends boolean = true> {
  status?: T;
  askType?: T;
  organizationName?: T;
  contactName?: T;
  email?: T;
  phone?: T;
  mission?: T;
  howHeard?: T;
  previousDonation?: T;
  eventName?: T;
  eventDate?: T;
  venue?: T;
  attendees?: T;
  requestDetails?: T;
  howServed?: T;
  recognition?: T;
  whyLolev?: T;
  pickupName?: T;
  taproom?: T;
  slackNotifiedAt?: T;
  slackError?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  location?: T;
  employmentType?: T;
  summary?: T;
  description?: T;
  closesOn?: T;
  active?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        keywords?: T;
        noIndex?: T;
        canonicalPath?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  job?: T;
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  slackNotifiedAt?: T;
  slackError?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recurring-events_select".
 */
export interface RecurringEventsSelect<T extends boolean = true> {
  active?: T;
  visibility?: T;
  organizer?: T;
  year?: T;
  day?: T;
  occurrences?: T;
  location?: T;
  startTime?: T;
  endTime?: T;
  excludedDates?:
    | T
    | {
        date?: T;
        id?: T;
      };
  site?: T;
  tags?: T;
  description?: T;
  image?: T;
  attendees?: T;
  pointOfContact?: T;
  email?: T;
  phone?: T;
  otherInfo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food_select".
 */
export interface FoodSelect<T extends boolean = true> {
  vendor?: T;
  vendorName?: T;
  date?: T;
  location?: T;
  startTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food-vendors_select".
 */
export interface FoodVendorsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  site?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recurring-food-schedules_select".
 */
export interface RecurringFoodSchedulesSelect<T extends boolean = true> {
  location?: T;
  year?: T;
  vendor?: T;
  day?: T;
  occurrence?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recurring-food-exclusions_select".
 */
export interface RecurringFoodExclusionsSelect<T extends boolean = true> {
  location?: T;
  date?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  slackUserId?: T;
  locations?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  markLinesCleanedToday?: T;
  linesLastCleaned?: T;
  active?: T;
  name?: T;
  draftMenu?: T;
  cansMenu?: T;
  intro?: T;
  timezone?: T;
  slug?: T;
  basicInfo?:
    | T
    | {
        phone?: T;
        email?: T;
      };
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
        directionsUrl?: T;
      };
  coordinates?: T;
  images?:
    | T
    | {
        card?: T;
        hero?: T;
      };
  monday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  tuesday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  wednesday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  thursday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  friday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  saturday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  sunday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        keywords?: T;
        noIndex?: T;
        canonicalPath?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "holiday-hours_select".
 */
export interface HolidayHoursSelect<T extends boolean = true> {
  name?: T;
  locations?: T;
  date?: T;
  type?: T;
  hours?:
    | T
    | {
        open?: T;
        close?: T;
      };
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributors_select".
 */
export interface DistributorsSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  city?: T;
  state?: T;
  zip?: T;
  customerType?: T;
  region?: T;
  location?: T;
  phone?: T;
  website?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        detail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  meta?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        parent?:
          | T
          | {
              taskSlug?: T;
              taskID?: T;
            };
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processingUntil?: T;
  processingToken?: T;
  concurrencyKey?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coming-soon".
 */
export interface ComingSoon {
  id: string;
  beers?:
    | {
        /**
         * Select the beer this entry refers to
         */
        beer?: (string | null) | Beer;
        /**
         * Select the beer style
         */
        style?: (string | null) | Style;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recurring-food".
 */
export interface RecurringFood {
  id: string;
  /**
   * Recurring food schedules by location ID
   */
  schedules?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Excluded dates by location ID
   */
  exclusions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Set after legacy JSON data has been migrated to native collections.
   */
  normalizedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content".
 */
export interface SiteContent {
  id: string;
  /**
   * Background image for the homepage hero section (recommended: 1920x1080px or larger)
   */
  heroImage?: (string | null) | Media;
  heroDescription?: string | null;
  aboutPhilosophy?: string | null;
  aboutLocations?: string | null;
  errorMessage?: string | null;
  todaysEventsTitle?: string | null;
  todaysFoodTitle?: string | null;
  /**
   * Sixth City/Encompass8 QuickLink URL for PA distributors
   */
  distributorPaUrl?: string | null;
  /**
   * Sixth City/Encompass8 QuickLink URL for OH distributors
   */
  distributorOhUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Default titles, descriptions, and social images. Per-page overrides for every static sitemap URL. Beer, location, and job pages use the SEO group on each document.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-seo".
 */
export interface SiteSeo {
  id: string;
  /**
   * Homepage / fallback <title>. Example: Lolev Beer • Craft Brewery in Zelienople & Pittsburgh
   */
  defaultTitle?: string | null;
  /**
   * Next.js title template with %s for the page title. Example: %s • Lolev Beer. Leave blank for "%s • Lolev Beer".
   */
  titleTemplate?: string | null;
  /**
   * Site-wide description when a page has none. Taproom names are still appended in code when this is blank.
   */
  description?: string | null;
  /**
   * Merged with location names on the root layout. Mostly legacy.
   */
  keywords?: string[] | null;
  /**
   * Fallback social card (1200×630). Replaces /images/beer/og-image.jpg when set.
   */
  ogImage?: (string | null) | Media;
  /**
   * e.g. @lolevbeer
   */
  twitterSite?: string | null;
  /**
   * e.g. @lolevbeer
   */
  twitterCreator?: string | null;
  pages?: {
    /**
     * Meta for Home (/). Blank fields keep the code defaults.
     */
    home?: {
      /**
       * Browser tab and SERP title. Leave blank to keep the auto-generated title. Do not append "• Lolev Beer" on hub pages; the site title template adds it.
       */
      title?: string | null;
      /**
       * SERP snippet. Aim for ~150–160 characters.
       */
      description?: string | null;
      /**
       * Optional. Defaults to the meta title (plus site name where applicable).
       */
      ogTitle?: string | null;
      /**
       * Optional. Defaults to the meta description.
       */
      ogDescription?: string | null;
      /**
       * Optional social share image (1200×630 recommended). Falls back to the site default.
       */
      ogImage?: (string | null) | Media;
      /**
       * Optional. Press Enter after each keyword. Mostly legacy; Google ignores these.
       */
      keywords?: string[] | null;
      /**
       * Ask search engines not to list this page in results. Links on it are still followed, and it is left out of the sitemap.
       */
      noIndex?: boolean | null;
    };
    /**
     * Meta for Beer catalog (/beer). Blank fields keep the code defaults.
     */
    beer?: {
      /**
       * Browser tab and SERP title. Leave blank to keep the auto-generated title. Do not append "• Lolev Beer" on hub pages; the site title template adds it.
       */
      title?: string | null;
      /**
       * SERP snippet. Aim for ~150–160 characters.
       */
      description?: string | null;
      /**
       * Optional. Defaults to the meta title (plus site name where applicable).
       */
      ogTitle?: string | null;
      /**
       * Optional. Defaults to the meta description.
       */
      ogDescription?: string | null;
      /**
       * Optional social share image (1200×630 recommended). Falls back to the site default.
       */
      ogImage?: (string | null) | Media;
      /**
       * Optional. Press Enter after each keyword. Mostly legacy; Google ignores these.
       */
      keywords?: string[] | null;
      /**
       * Ask search engines not to list this page in results. Links on it are still followed, and it is left out of the sitemap.
       */
      noIndex?: boolean | null;
      /**
       * Optional short paragraph shown under the page heading (Beer, Events, Food). Good for search and AI answers; leave blank to show nothing.
       */
      intro?: string | null;
    };
    /**
     * Meta for Events (/events). Blank fields keep the code defaults.
     */
    events?: {
      /**
       * Browser tab and SERP title. Leave blank to keep the auto-generated title. Do not append "• Lolev Beer" on hub pages; the site title template adds it.
       */
      title?: string | null;
      /**
       * SERP snippet. Aim for ~150–160 characters.
       */
      description?: string | null;
      /**
       * Optional. Defaults to the meta title (plus site name where applicable).
       */
      ogTitle?: string | null;
      /**
       * Optional. Defaults to the meta description.
       */
      ogDescription?: string | null;
      /**
       * Optional social share image (1200×630 recommended). Falls back to the site default.
       */
      ogImage?: (string | null) | Media;
      /**
       * Optional. Press Enter after each keyword. Mostly legacy; Google ignores these.
       */
      keywords?: string[] | null;
      /**
       * Ask search engines not to list this page in results. Links on it are still followed, and it is left out of the sitemap.
       */
      noIndex?: boolean | null;
      /**
       * Optional short paragraph shown under the page heading (Beer, Events, Food). Good for search and AI answers; leave blank to show nothing.
       */
      intro?: string | null;
    };
    /**
     * Meta for Food (/food). Blank fields keep the code defaults.
     */
    food?: {
      /**
       * Browser tab and SERP title. Leave blank to keep the auto-generated title. Do not append "• Lolev Beer" on hub pages; the site title template adds it.
       */
      title?: string | null;
      /**
       * SERP snippet. Aim for ~150–160 characters.
       */
      description?: string | null;
      /**
       * Optional. Defaults to the meta title (plus site name where applicable).
       */
      ogTitle?: string | null;
      /**
       * Optional. Defaults to the meta description.
       */
      ogDescription?: string | null;
      /**
       * Optional social share image (1200×630 recommended). Falls back to the site default.
       */
      ogImage?: (string | null) | Media;
      /**
       * Optional. Press Enter after each keyword. Mostly legacy; Google ignores these.
       */
      keywords?: string[] | null;
      /**
       * Ask search engines not to list this page in results. Links on it are still followed, and it is left out of the sitemap.
       */
      noIndex?: boolean | null;
      /**
       * Optional short paragraph shown under the page heading (Beer, Events, Food). Good for search and AI answers; leave blank to show nothing.
       */
      intro?: string | null;
    };
    /**
     * Meta for Beer map (/beer-map). Blank fields keep the code defaults.
     */
    beerMap?: {
      /**
       * Browser tab and SERP title. Leave blank to keep the auto-generated title. Do not append "• Lolev Beer" on hub pages; the site title template adds it.
       */
      title?: string | null;
      /**
       * SERP snippet. Aim for ~150–160 characters.
       */
      description?: string | null;
      /**
       * Optional. Defaults to the meta title (plus site name where applicable).
       */
      ogTitle?: string | null;
      /**
       * Optional. Defaults to the meta description.
       */
      ogDescription?: string | null;
      /**
       * Optional social share image (1200×630 recommended). Falls back to the site default.
       */
      ogImage?: (string | null) | Media;
      /**
       * Optional. Press Enter after each keyword. Mostly legacy; Google ignores these.
       */
      keywords?: string[] | null;
      /**
       * Ask search engines not to list this page in results. Links on it are still followed, and it is left out of the sitemap.
       */
      noIndex?: boolean | null;
    };
    /**
     * Meta for Donations (/donate). Blank fields keep the code defaults.
     */
    donate?: {
      /**
       * Browser tab and SERP title. Leave blank to keep the auto-generated title. Do not append "• Lolev Beer" on hub pages; the site title template adds it.
       */
      title?: string | null;
      /**
       * SERP snippet. Aim for ~150–160 characters.
       */
      description?: string | null;
      /**
       * Optional. Defaults to the meta title (plus site name where applicable).
       */
      ogTitle?: string | null;
      /**
       * Optional. Defaults to the meta description.
       */
      ogDescription?: string | null;
      /**
       * Optional social share image (1200×630 recommended). Falls back to the site default.
       */
      ogImage?: (string | null) | Media;
      /**
       * Optional. Press Enter after each keyword. Mostly legacy; Google ignores these.
       */
      keywords?: string[] | null;
      /**
       * Ask search engines not to list this page in results. Links on it are still followed, and it is left out of the sitemap.
       */
      noIndex?: boolean | null;
    };
    /**
     * Meta for Jobs list (/jobs). Blank fields keep the code defaults.
     */
    jobs?: {
      /**
       * Browser tab and SERP title. Leave blank to keep the auto-generated title. Do not append "• Lolev Beer" on hub pages; the site title template adds it.
       */
      title?: string | null;
      /**
       * SERP snippet. Aim for ~150–160 characters.
       */
      description?: string | null;
      /**
       * Optional. Defaults to the meta title (plus site name where applicable).
       */
      ogTitle?: string | null;
      /**
       * Optional. Defaults to the meta description.
       */
      ogDescription?: string | null;
      /**
       * Optional social share image (1200×630 recommended). Falls back to the site default.
       */
      ogImage?: (string | null) | Media;
      /**
       * Optional. Press Enter after each keyword. Mostly legacy; Google ignores these.
       */
      keywords?: string[] | null;
      /**
       * Ask search engines not to list this page in results. Links on it are still followed, and it is left out of the sitemap.
       */
      noIndex?: boolean | null;
    };
    /**
     * Meta for About (/about). Blank fields keep the code defaults.
     */
    about?: {
      /**
       * Browser tab and SERP title. Leave blank to keep the auto-generated title. Do not append "• Lolev Beer" on hub pages; the site title template adds it.
       */
      title?: string | null;
      /**
       * SERP snippet. Aim for ~150–160 characters.
       */
      description?: string | null;
      /**
       * Optional. Defaults to the meta title (plus site name where applicable).
       */
      ogTitle?: string | null;
      /**
       * Optional. Defaults to the meta description.
       */
      ogDescription?: string | null;
      /**
       * Optional social share image (1200×630 recommended). Falls back to the site default.
       */
      ogImage?: (string | null) | Media;
      /**
       * Optional. Press Enter after each keyword. Mostly legacy; Google ignores these.
       */
      keywords?: string[] | null;
      /**
       * Ask search engines not to list this page in results. Links on it are still followed, and it is left out of the sitemap.
       */
      noIndex?: boolean | null;
    };
    /**
     * Meta for FAQ (/faq). Blank fields keep the code defaults.
     */
    faq?: {
      /**
       * Browser tab and SERP title. Leave blank to keep the auto-generated title. Do not append "• Lolev Beer" on hub pages; the site title template adds it.
       */
      title?: string | null;
      /**
       * SERP snippet. Aim for ~150–160 characters.
       */
      description?: string | null;
      /**
       * Optional. Defaults to the meta title (plus site name where applicable).
       */
      ogTitle?: string | null;
      /**
       * Optional. Defaults to the meta description.
       */
      ogDescription?: string | null;
      /**
       * Optional social share image (1200×630 recommended). Falls back to the site default.
       */
      ogImage?: (string | null) | Media;
      /**
       * Optional. Press Enter after each keyword. Mostly legacy; Google ignores these.
       */
      keywords?: string[] | null;
      /**
       * Ask search engines not to list this page in results. Links on it are still followed, and it is left out of the sitemap.
       */
      noIndex?: boolean | null;
    };
    /**
     * Meta for Accessibility (/accessibility). Blank fields keep the code defaults.
     */
    accessibility?: {
      /**
       * Browser tab and SERP title. Leave blank to keep the auto-generated title. Do not append "• Lolev Beer" on hub pages; the site title template adds it.
       */
      title?: string | null;
      /**
       * SERP snippet. Aim for ~150–160 characters.
       */
      description?: string | null;
      /**
       * Optional. Defaults to the meta title (plus site name where applicable).
       */
      ogTitle?: string | null;
      /**
       * Optional. Defaults to the meta description.
       */
      ogDescription?: string | null;
      /**
       * Optional social share image (1200×630 recommended). Falls back to the site default.
       */
      ogImage?: (string | null) | Media;
      /**
       * Optional. Press Enter after each keyword. Mostly legacy; Google ignores these.
       */
      keywords?: string[] | null;
      /**
       * Ask search engines not to list this page in results. Links on it are still followed, and it is left out of the sitemap.
       */
      noIndex?: boolean | null;
    };
    /**
     * Meta for Privacy (/privacy). Blank fields keep the code defaults.
     */
    privacy?: {
      /**
       * Browser tab and SERP title. Leave blank to keep the auto-generated title. Do not append "• Lolev Beer" on hub pages; the site title template adds it.
       */
      title?: string | null;
      /**
       * SERP snippet. Aim for ~150–160 characters.
       */
      description?: string | null;
      /**
       * Optional. Defaults to the meta title (plus site name where applicable).
       */
      ogTitle?: string | null;
      /**
       * Optional. Defaults to the meta description.
       */
      ogDescription?: string | null;
      /**
       * Optional social share image (1200×630 recommended). Falls back to the site default.
       */
      ogImage?: (string | null) | Media;
      /**
       * Optional. Press Enter after each keyword. Mostly legacy; Google ignores these.
       */
      keywords?: string[] | null;
      /**
       * Ask search engines not to list this page in results. Links on it are still followed, and it is left out of the sitemap.
       */
      noIndex?: boolean | null;
    };
    /**
     * Meta for Terms (/terms). Blank fields keep the code defaults.
     */
    terms?: {
      /**
       * Browser tab and SERP title. Leave blank to keep the auto-generated title. Do not append "• Lolev Beer" on hub pages; the site title template adds it.
       */
      title?: string | null;
      /**
       * SERP snippet. Aim for ~150–160 characters.
       */
      description?: string | null;
      /**
       * Optional. Defaults to the meta title (plus site name where applicable).
       */
      ogTitle?: string | null;
      /**
       * Optional. Defaults to the meta description.
       */
      ogDescription?: string | null;
      /**
       * Optional social share image (1200×630 recommended). Falls back to the site default.
       */
      ogImage?: (string | null) | Media;
      /**
       * Optional. Press Enter after each keyword. Mostly legacy; Google ignores these.
       */
      keywords?: string[] | null;
      /**
       * Ask search engines not to list this page in results. Links on it are still followed, and it is left out of the sitemap.
       */
      noIndex?: boolean | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coming-soon_select".
 */
export interface ComingSoonSelect<T extends boolean = true> {
  beers?:
    | T
    | {
        beer?: T;
        style?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recurring-food_select".
 */
export interface RecurringFoodSelect<T extends boolean = true> {
  schedules?: T;
  exclusions?: T;
  normalizedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content_select".
 */
export interface SiteContentSelect<T extends boolean = true> {
  heroImage?: T;
  heroDescription?: T;
  aboutPhilosophy?: T;
  aboutLocations?: T;
  errorMessage?: T;
  todaysEventsTitle?: T;
  todaysFoodTitle?: T;
  distributorPaUrl?: T;
  distributorOhUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-seo_select".
 */
export interface SiteSeoSelect<T extends boolean = true> {
  defaultTitle?: T;
  titleTemplate?: T;
  description?: T;
  keywords?: T;
  ogImage?: T;
  twitterSite?: T;
  twitterCreator?: T;
  pages?:
    | T
    | {
        home?:
          | T
          | {
              title?: T;
              description?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              keywords?: T;
              noIndex?: T;
            };
        beer?:
          | T
          | {
              title?: T;
              description?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              keywords?: T;
              noIndex?: T;
              intro?: T;
            };
        events?:
          | T
          | {
              title?: T;
              description?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              keywords?: T;
              noIndex?: T;
              intro?: T;
            };
        food?:
          | T
          | {
              title?: T;
              description?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              keywords?: T;
              noIndex?: T;
              intro?: T;
            };
        beerMap?:
          | T
          | {
              title?: T;
              description?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              keywords?: T;
              noIndex?: T;
            };
        donate?:
          | T
          | {
              title?: T;
              description?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              keywords?: T;
              noIndex?: T;
            };
        jobs?:
          | T
          | {
              title?: T;
              description?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              keywords?: T;
              noIndex?: T;
            };
        about?:
          | T
          | {
              title?: T;
              description?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              keywords?: T;
              noIndex?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              description?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              keywords?: T;
              noIndex?: T;
            };
        accessibility?:
          | T
          | {
              title?: T;
              description?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              keywords?: T;
              noIndex?: T;
            };
        privacy?:
          | T
          | {
              title?: T;
              description?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              keywords?: T;
              noIndex?: T;
            };
        terms?:
          | T
          | {
              title?: T;
              description?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              keywords?: T;
              noIndex?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-query_widget".
 */
export interface CollectionQueryWidget {
  data?: {
    title?: string | null;
    relatedCollection:
      | 'beers'
      | 'beer-reviews'
      | 'menus'
      | 'products'
      | 'events'
      | 'donation-requests'
      | 'jobs'
      | 'job-applications'
      | 'recurring-events'
      | 'food'
      | 'food-vendors'
      | 'users'
      | 'locations'
      | 'holiday-hours'
      | 'distributors'
      | 'faqs'
      | 'payload-jobs';
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    sortField?: string | null;
    sortDirection?: ('asc' | 'desc') | null;
    limit?: number | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_widget".
 */
export interface ActivityWidget {
  data?: {
    excludedCollections?:
      | (
          | 'beers'
          | 'beer-reviews'
          | 'menus'
          | 'products'
          | 'events'
          | 'donation-requests'
          | 'jobs'
          | 'job-applications'
          | 'recurring-events'
          | 'food'
          | 'food-vendors'
          | 'users'
          | 'locations'
          | 'holiday-hours'
          | 'distributors'
          | 'faqs'
          | 'payload-jobs'
        )[]
      | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncUntappdRatings".
 */
export interface TaskSyncUntappdRatings {
  input?: unknown;
  output: {
    total: number;
    updated: number;
    skipped: number;
    errors: number;
    unavailable: number;
    circuitBroken: boolean;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}