/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    styles: Style;
    beers: Beer;
    events: Event;
    food: Food;
    locations: Location;
    'holiday-hours': HolidayHour;
    menus: Menu;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    styles: StylesSelect<false> | StylesSelect<true>;
    beers: BeersSelect<false> | BeersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    food: FoodSelect<false> | FoodSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'holiday-hours': HolidayHoursSelect<false> | HolidayHoursSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'coming-soon': ComingSoon;
    'site-content': SiteContent;
  };
  globalsSelect: {
    'coming-soon': ComingSoonSelect<false> | ComingSoonSelect<true>;
    'site-content': SiteContentSelect<false> | SiteContentSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alternative text for the image (for accessibility)
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    detail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "styles".
 */
export interface Style {
  id: string;
  /**
   * Beer style name (e.g., IPA, Stout, Pale Ale)
   */
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beers".
 */
export interface Beer {
  id: string;
  glass: 'pint' | 'stein' | 'teku';
  /**
   * Alcohol by volume percentage
   */
  abv: number;
  /**
   * Draft price in dollars (e.g., 7)
   */
  draftPrice: number;
  /**
   * Four pack price (e.g., 15)
   */
  fourPack?: number | null;
  /**
   * Auto-calculated from four pack price
   */
  canSingle?: number | null;
  /**
   * UPC barcode
   */
  upc?: string | null;
  /**
   * Auto-generated from name, but you can override it manually
   */
  slug: string;
  /**
   * Auto-incremented recipe number
   */
  recipe?: number | null;
  hideFromSite?: boolean | null;
  name: string;
  /**
   * Beer style
   */
  style: string | Style;
  /**
   * Beer image (recommended: 2500x2500px)
   */
  image?: (string | null) | Media;
  description?: string | null;
  /**
   * Hop varieties used
   */
  hops?: string | null;
  /**
   * Untappd URL
   */
  untappd?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  /**
   * Event or vendor name
   */
  vendor: string;
  date: string;
  /**
   * Time range (e.g., "4-9pm" or "7:30pm")
   */
  time?: string | null;
  /**
   * End time if different format needed
   */
  endTime?: string | null;
  location: string | Location;
  visibility: 'public' | 'private';
  /**
   * Website or social media link
   */
  site?: string | null;
  /**
   * Event description (optional)
   */
  description?: string | null;
  /**
   * Expected or registered attendees
   */
  attendees?: number | null;
  /**
   * Where this record originated
   */
  source?: ('payload' | 'google-sheets') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: string;
  /**
   * Is this location currently active?
   */
  active?: boolean | null;
  name: string;
  /**
   * Timezone for this location's hours
   */
  timezone?: ('America/New_York' | 'America/Chicago' | 'America/Denver' | 'America/Los_Angeles') | null;
  /**
   * Auto-generated from name (lowercase, spaces to dashes)
   */
  slug?: string | null;
  basicInfo?: {
    phone?: string | null;
    email?: string | null;
  };
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  monday?: {
    open?: string | null;
    close?: string | null;
  };
  tuesday?: {
    open?: string | null;
    close?: string | null;
  };
  wednesday?: {
    open?: string | null;
    close?: string | null;
  };
  thursday?: {
    open?: string | null;
    close?: string | null;
  };
  friday?: {
    open?: string | null;
    close?: string | null;
  };
  saturday?: {
    open?: string | null;
    close?: string | null;
  };
  sunday?: {
    open?: string | null;
    close?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food".
 */
export interface Food {
  id: string;
  /**
   * Food vendor name
   */
  vendor: string;
  date: string;
  /**
   * Service time (e.g., "4-9pm")
   */
  time: string;
  location: string | Location;
  /**
   * Website or social media link
   */
  site?: string | null;
  /**
   * Day of week
   */
  day?: ('Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday') | null;
  /**
   * Start time (e.g., "4pm")
   */
  start?: string | null;
  /**
   * End time (e.g., "9pm")
   */
  finish?: string | null;
  /**
   * Week number
   */
  week?: number | null;
  /**
   * Day number (1-7)
   */
  dayNumber?: number | null;
  /**
   * Where this record originated
   */
  source?: ('payload' | 'google-sheets') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Holiday and special hours overrides for locations
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "holiday-hours".
 */
export interface HolidayHour {
  id: string;
  /**
   * Name for this override (e.g., "Christmas Day", "New Year's Eve")
   */
  name: string;
  /**
   * Which location(s) this override applies to
   */
  locations: (string | Location)[];
  /**
   * The date this override applies to
   */
  date: string;
  /**
   * Type of override
   */
  type: 'closed' | 'modified';
  /**
   * Override hours (only used when type is "Modified Hours")
   */
  hours?: {
    /**
     * Opening time
     */
    open?: string | null;
    /**
     * Closing time
     */
    close?: string | null;
  };
  /**
   * Optional note to display (e.g., "Closed for the holiday")
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: string;
  /**
   * Menu name (e.g., "Lawrenceville Draft Menu")
   */
  name: string;
  /**
   * Menu description
   */
  description?: string | null;
  /**
   * Required to generate menu URL
   */
  location: string | Location;
  type: 'cans' | 'draft' | 'other';
  /**
   * Auto-generated from location and type, but you can override it manually
   */
  url: string;
  items: {
    /**
     * Search by name or slug
     */
    beer: string | Beer;
    /**
     * Sale Price
     */
    price?: string | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'styles';
        value: string | Style;
      } | null)
    | ({
        relationTo: 'beers';
        value: string | Beer;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'food';
        value: string | Food;
      } | null)
    | ({
        relationTo: 'locations';
        value: string | Location;
      } | null)
    | ({
        relationTo: 'holiday-hours';
        value: string | HolidayHour;
      } | null)
    | ({
        relationTo: 'menus';
        value: string | Menu;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        detail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "styles_select".
 */
export interface StylesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beers_select".
 */
export interface BeersSelect<T extends boolean = true> {
  glass?: T;
  abv?: T;
  draftPrice?: T;
  fourPack?: T;
  canSingle?: T;
  upc?: T;
  slug?: T;
  recipe?: T;
  hideFromSite?: T;
  name?: T;
  style?: T;
  image?: T;
  description?: T;
  hops?: T;
  untappd?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  vendor?: T;
  date?: T;
  time?: T;
  endTime?: T;
  location?: T;
  visibility?: T;
  site?: T;
  description?: T;
  attendees?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food_select".
 */
export interface FoodSelect<T extends boolean = true> {
  vendor?: T;
  date?: T;
  time?: T;
  location?: T;
  site?: T;
  day?: T;
  start?: T;
  finish?: T;
  week?: T;
  dayNumber?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  active?: T;
  name?: T;
  timezone?: T;
  slug?: T;
  basicInfo?:
    | T
    | {
        phone?: T;
        email?: T;
      };
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  monday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  tuesday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  wednesday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  thursday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  friday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  saturday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  sunday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "holiday-hours_select".
 */
export interface HolidayHoursSelect<T extends boolean = true> {
  name?: T;
  locations?: T;
  date?: T;
  type?: T;
  hours?:
    | T
    | {
        open?: T;
        close?: T;
      };
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  location?: T;
  type?: T;
  url?: T;
  items?:
    | T
    | {
        beer?: T;
        price?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coming-soon".
 */
export interface ComingSoon {
  id: string;
  beers?:
    | {
        /**
         * Select the beer this entry refers to
         */
        beer?: (string | null) | Beer;
        /**
         * Select the beer style
         */
        style?: (string | null) | Style;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content".
 */
export interface SiteContent {
  id: string;
  heroDescription?: string | null;
  errorMessage?: string | null;
  todaysEventsTitle?: string | null;
  todaysFoodTitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coming-soon_select".
 */
export interface ComingSoonSelect<T extends boolean = true> {
  beers?:
    | T
    | {
        beer?: T;
        style?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content_select".
 */
export interface SiteContentSelect<T extends boolean = true> {
  heroDescription?: T;
  errorMessage?: T;
  todaysEventsTitle?: T;
  todaysFoodTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}