/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    beers: Beer;
    styles: Style;
    menus: Menu;
    products: Product;
    events: Event;
    food: Food;
    'food-vendors': FoodVendor;
    users: User;
    locations: Location;
    'holiday-hours': HolidayHour;
    distributors: Distributor;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    beers: BeersSelect<false> | BeersSelect<true>;
    styles: StylesSelect<false> | StylesSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    food: FoodSelect<false> | FoodSelect<true>;
    'food-vendors': FoodVendorsSelect<false> | FoodVendorsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'holiday-hours': HolidayHoursSelect<false> | HolidayHoursSelect<true>;
    distributors: DistributorsSelect<false> | DistributorsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'coming-soon': ComingSoon;
    'recurring-food': RecurringFood;
    'site-content': SiteContent;
  };
  globalsSelect: {
    'coming-soon': ComingSoonSelect<false> | ComingSoonSelect<true>;
    'recurring-food': RecurringFoodSelect<false> | RecurringFoodSelect<true>;
    'site-content': SiteContentSelect<false> | SiteContentSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beers".
 */
export interface Beer {
  id: string;
  glass: 'pint' | 'stein' | 'teku';
  /**
   * Alcohol by volume percentage
   */
  abv: number;
  /**
   * Draft price in dollars (e.g., 7)
   */
  draftPrice: number;
  /**
   * Enable to manually set half pour price (disables auto-calculation)
   */
  halfPourOnly?: boolean | null;
  /**
   * Auto-calculated unless "Half Pour Only" is enabled
   */
  halfPour?: number | null;
  /**
   * Four pack price (e.g., 15)
   */
  fourPack?: number | null;
  /**
   * Auto-calculated from four pack price
   */
  canSingle?: number | null;
  /**
   * UPC barcode
   */
  upc?: string | null;
  /**
   * Auto-generated from name, but you can override it manually
   */
  slug: string;
  /**
   * Auto-incremented recipe number
   */
  recipe?: number | null;
  hideFromSite?: boolean | null;
  /**
   * Mark as "Just Released". If no beers have this set, beers created within 2 weeks are auto-marked.
   */
  justReleased?: boolean | null;
  name: string;
  /**
   * Beer style
   */
  style: string | Style;
  /**
   * Beer image (recommended: 2500x2500px)
   */
  image?: (string | null) | Media;
  description?: string | null;
  /**
   * Hop varieties used
   */
  hops?: string | null;
  /**
   * Untappd URL
   */
  untappd?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "styles".
 */
export interface Style {
  id: string;
  /**
   * Beer style name (e.g., IPA, Stout, Pale Ale)
   */
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alternative text for the image (for accessibility)
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    detail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: string;
  /**
   * Menu name (e.g., "Lawrenceville Draft Menu")
   */
  name: string;
  /**
   * Menu description
   */
  description?: string | null;
  /**
   * Required to generate menu URL
   */
  location: string | Location;
  type: 'cans' | 'draft' | 'other';
  /**
   * Auto-generated from location and type, but you can override it manually
   */
  url: string;
  /**
   * Google Sheets CSV export URL for syncing this menu (optional)
   */
  sheetUrl?: string | null;
  items: {
    product:
      | {
          relationTo: 'beers';
          value: string | Beer;
        }
      | {
          relationTo: 'products';
          value: string | Product;
        };
    /**
     * Sale Price (optional override)
     */
    price?: string | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: string;
  /**
   * Is this location currently active?
   */
  active?: boolean | null;
  name: string;
  /**
   * Timezone for this location's hours
   */
  timezone?: ('America/New_York' | 'America/Chicago' | 'America/Denver' | 'America/Los_Angeles') | null;
  /**
   * Auto-generated from name (lowercase, spaces to dashes)
   */
  slug?: string | null;
  /**
   * CSV export URLs for syncing data from Google Sheets
   */
  googleSheets?: {
    /**
     * Public events (concerts, trivia, etc.)
     */
    eventsPublic?: string | null;
    /**
     * Private events (rentals, corporate, etc.)
     */
    eventsPrivate?: string | null;
    /**
     * Food truck schedule
     */
    food?: string | null;
    /**
     * Operating hours schedule
     */
    hours?: string | null;
  };
  basicInfo?: {
    phone?: string | null;
    email?: string | null;
  };
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
    /**
     * Custom Google Maps or directions link for this location
     */
    directionsUrl?: string | null;
  };
  /**
   * Longitude, Latitude (e.g. -79.960098, 40.465372)
   *
   * @minItems 2
   * @maxItems 2
   */
  coordinates?: [number, number] | null;
  images?: {
    /**
     * Image shown on location cards (recommended: 800x600px)
     */
    card?: (string | null) | Media;
    /**
     * Hero/banner image for this location (recommended: 1920x1080px)
     */
    hero?: (string | null) | Media;
  };
  monday?: {
    open?: string | null;
    close?: string | null;
  };
  tuesday?: {
    open?: string | null;
    close?: string | null;
  };
  wednesday?: {
    open?: string | null;
    close?: string | null;
  };
  thursday?: {
    open?: string | null;
    close?: string | null;
  };
  friday?: {
    open?: string | null;
    close?: string | null;
  };
  saturday?: {
    open?: string | null;
    close?: string | null;
  };
  sunday?: {
    open?: string | null;
    close?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  /**
   * Press "Enter" or "Tab" after entering option to add another
   */
  options?: string[] | null;
  /**
   * Alcohol by volume (%)
   */
  abv?: number | null;
  /**
   * Display price (e.g., "$5.00")
   */
  price?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  /**
   * Public events will be displayed on the site
   */
  visibility: 'public' | 'private';
  /**
   * If this is a public event, this will be listed on the website
   */
  organizer: string;
  date: string;
  startTime?: string | null;
  endTime?: string | null;
  location: string | Location;
  /**
   * This will be linked on the website
   */
  site?: string | null;
  description?: string | null;
  /**
   * Expected or registered attendees
   */
  attendees?: number | null;
  pointOfContact?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Additional information for private event
   */
  otherInfo?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food".
 */
export interface Food {
  id: string;
  /**
   * Select food vendor
   */
  vendor: string | FoodVendor;
  /**
   * Auto-populated vendor name for display
   */
  vendorName?: string | null;
  date: string;
  location: string | Location;
  startTime?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food-vendors".
 */
export interface FoodVendor {
  id: string;
  name: string;
  email?: string | null;
  phone?: string | null;
  site?: string | null;
  logo?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  /**
   * Assign to specific locations. If set, bartenders can only access menus for these locations.
   */
  locations?: (string | Location)[] | null;
  /**
   * Admins can manage users and all content. Event/Beer/Food Managers can manage their respective collections. Bartenders can update menus. Users can have multiple roles.
   */
  roles: ('admin' | 'event-manager' | 'beer-manager' | 'food-manager' | 'bartender')[];
  role?: ('admin' | 'event-manager' | 'beer-manager' | 'food-manager' | 'bartender') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Holiday and special hours overrides for locations
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "holiday-hours".
 */
export interface HolidayHour {
  id: string;
  /**
   * Name for this override (e.g., "Christmas Day", "New Year's Eve")
   */
  name: string;
  /**
   * Which location(s) this override applies to
   */
  locations: (string | Location)[];
  /**
   * The date this override applies to
   */
  date: string;
  /**
   * Type of override
   */
  type: 'closed' | 'modified';
  /**
   * Override hours (only used when type is "Modified Hours")
   */
  hours?: {
    /**
     * Opening time
     */
    open?: string | null;
    /**
     * Closing time
     */
    close?: string | null;
  };
  /**
   * Optional note to display (e.g., "Closed for the holiday")
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributors".
 */
export interface Distributor {
  id: string;
  /**
   * Business or location name
   */
  name: string;
  /**
   * Full street address
   */
  address: string;
  /**
   * City name
   */
  city?: string | null;
  /**
   * State abbreviation (e.g., PA, NY)
   */
  state?: string | null;
  /**
   * ZIP code
   */
  zip?: string | null;
  /**
   * Type of customer/location
   */
  customerType?: ('Retail' | 'On Premise' | 'Home-D') | null;
  /**
   * Geographic region
   */
  region?: ('NY' | 'OH' | 'PA' | 'WV') | null;
  /**
   * Geographic coordinates [longitude, latitude]
   *
   * @minItems 2
   * @maxItems 2
   */
  location: [number, number];
  /**
   * Contact phone number
   */
  phone?: string | null;
  /**
   * Website URL
   */
  website?: string | null;
  /**
   * Whether this location is currently active
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'beers';
        value: string | Beer;
      } | null)
    | ({
        relationTo: 'styles';
        value: string | Style;
      } | null)
    | ({
        relationTo: 'menus';
        value: string | Menu;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'food';
        value: string | Food;
      } | null)
    | ({
        relationTo: 'food-vendors';
        value: string | FoodVendor;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'locations';
        value: string | Location;
      } | null)
    | ({
        relationTo: 'holiday-hours';
        value: string | HolidayHour;
      } | null)
    | ({
        relationTo: 'distributors';
        value: string | Distributor;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beers_select".
 */
export interface BeersSelect<T extends boolean = true> {
  glass?: T;
  abv?: T;
  draftPrice?: T;
  halfPourOnly?: T;
  halfPour?: T;
  fourPack?: T;
  canSingle?: T;
  upc?: T;
  slug?: T;
  recipe?: T;
  hideFromSite?: T;
  justReleased?: T;
  name?: T;
  style?: T;
  image?: T;
  description?: T;
  hops?: T;
  untappd?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "styles_select".
 */
export interface StylesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  location?: T;
  type?: T;
  url?: T;
  sheetUrl?: T;
  items?:
    | T
    | {
        product?: T;
        price?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  options?: T;
  abv?: T;
  price?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  visibility?: T;
  organizer?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  location?: T;
  site?: T;
  description?: T;
  attendees?: T;
  pointOfContact?: T;
  email?: T;
  phone?: T;
  otherInfo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food_select".
 */
export interface FoodSelect<T extends boolean = true> {
  vendor?: T;
  vendorName?: T;
  date?: T;
  location?: T;
  startTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food-vendors_select".
 */
export interface FoodVendorsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  site?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  locations?: T;
  roles?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  active?: T;
  name?: T;
  timezone?: T;
  slug?: T;
  googleSheets?:
    | T
    | {
        eventsPublic?: T;
        eventsPrivate?: T;
        food?: T;
        hours?: T;
      };
  basicInfo?:
    | T
    | {
        phone?: T;
        email?: T;
      };
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
        directionsUrl?: T;
      };
  coordinates?: T;
  images?:
    | T
    | {
        card?: T;
        hero?: T;
      };
  monday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  tuesday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  wednesday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  thursday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  friday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  saturday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  sunday?:
    | T
    | {
        open?: T;
        close?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "holiday-hours_select".
 */
export interface HolidayHoursSelect<T extends boolean = true> {
  name?: T;
  locations?: T;
  date?: T;
  type?: T;
  hours?:
    | T
    | {
        open?: T;
        close?: T;
      };
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributors_select".
 */
export interface DistributorsSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  city?: T;
  state?: T;
  zip?: T;
  customerType?: T;
  region?: T;
  location?: T;
  phone?: T;
  website?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        detail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coming-soon".
 */
export interface ComingSoon {
  id: string;
  beers?:
    | {
        /**
         * Select the beer this entry refers to
         */
        beer?: (string | null) | Beer;
        /**
         * Select the beer style
         */
        style?: (string | null) | Style;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recurring-food".
 */
export interface RecurringFood {
  id: string;
  /**
   * Recurring food schedules by location ID
   */
  schedules?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Excluded dates by location ID
   */
  exclusions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content".
 */
export interface SiteContent {
  id: string;
  /**
   * Background image for the homepage hero section (recommended: 1920x1080px or larger)
   */
  heroImage?: (string | null) | Media;
  heroDescription?: string | null;
  errorMessage?: string | null;
  todaysEventsTitle?: string | null;
  todaysFoodTitle?: string | null;
  /**
   * Sixth City/Encompass8 QuickLink URL for PA distributors
   */
  distributorPaUrl?: string | null;
  /**
   * Sixth City/Encompass8 QuickLink URL for OH distributors
   */
  distributorOhUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coming-soon_select".
 */
export interface ComingSoonSelect<T extends boolean = true> {
  beers?:
    | T
    | {
        beer?: T;
        style?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recurring-food_select".
 */
export interface RecurringFoodSelect<T extends boolean = true> {
  schedules?: T;
  exclusions?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content_select".
 */
export interface SiteContentSelect<T extends boolean = true> {
  heroImage?: T;
  heroDescription?: T;
  errorMessage?: T;
  todaysEventsTitle?: T;
  todaysFoodTitle?: T;
  distributorPaUrl?: T;
  distributorOhUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}