name: Process JSON and Fetch Geocode

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          lfs: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests geopy python-dotenv

      - name: Process JSON
        continue-on-error: true
        env:
          BING: ${{ vars.BING }}
          SARENE_LOCATIONS: ${{ vars.SARENE_LOCATIONS }}
        run: |
          cd assets
          python process_json.py
          git config --local user.email "info@lolev.beer"
          git config --local user.name "Map Manager"
          git add .
          git commit -m "Process new address updates"
          git push
