name: Update Map

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  repository_dispatch:
    types: [update-map]
  workflow_dispatch:  # Allows manual triggering

# Add concurrency group
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ github.token }}
          lfs: false

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Process JSON and commit changes
        continue-on-error: true
        env:
          BING: ${{ vars.BING }}
          SARENE_LOCATIONS: ${{ vars.SARENE_LOCATIONS }}
        run: |
          cd public/data
          python ../../scripts/process_json.py
          git config --local user.email "info@lolev.beer"
          git config --local user.name "Map Manager"
          git add processed_geo_data.json ny_geo_data.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Process new address updates"
          git push
