name: Check Files for errors

on:
  pull_request:
    branches:
      - master

jobs:
  yml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install yamllint csvkit

    - name: Lint YAML files
      run: |
        yamllint -d "{extends: relaxed, rules: {line-length: {max: 140}}}" _data/.

    - name: Lint CSV files
      run: |
        find _data/. -name "*.csv" -print0 | xargs -0 csvclean -n

    # - name: Upload results
    #   if: always()
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: lint-results
    #     path: .
